name: clean_architecture_tdd
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  data_connection_checker: ^0.3.4
  dartz: ^0.8.6 # Functional programming things
  equatable: ^0.4.0 # Value equality
  flutter_bloc: ^0.21.0 # Bloc for state management
  get_it: ^2.0.1 # Service locator
  http: ^0.12.0+2 # Remote api
  shared_preferences: ^0.5.3+4 # Local chace

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.0

flutter:
  uses-material-design: true